import React from "react";
import { Layout } from "@/components/Layout";
import { PageHeader } from "@/components/PageHeader";
import { PageEnter, Stagger, StaggerItem, ChartReveal } from "@/components/motion";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Printer, TrendingUp, BarChart3, Activity } from "lucide-react";
import { useFederalData } from "@/lib/FederalDataContext";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, AreaChart, Area } from "recharts";
import { CAPABILITY_LEVELS } from "@/lib/constants";

export default function ManagerReports() {
  const { focus, teamOf, submissions } = useFederalData();
  const team = teamOf(focus.managerId);
  const teamIds = new Set(team.map(p => p.id));
  
  const teamSubmissions = submissions.filter(s => teamIds.has(s.personId) && (s.state === 'endorsed' || s.state === 'deployed'));
  
  const capabilityDistribution = CAPABILITY_LEVELS.map((level, index) => ({
    name: level.label.replace("Emerging Practitioner", "Emerging"),
    count: team.filter((p) => p.levelId === level.id).length,
    fill: ["hsl(var(--muted-foreground))", "hsl(var(--secondary))", "hsl(var(--primary))", "hsl(var(--accent))", "hsl(var(--chart-4))"][index],
  }));

  const hoursSaved = teamSubmissions.reduce((acc, s) => acc + s.hoursSavedPerMonth, 0);
  const valueCreated = teamSubmissions.reduce((acc, s) => acc + s.estimatedValueAed, 0);

  const avgProgress = team.length ? Math.round(team.reduce((a, p) => a + p.pathwayProgress, 0) / team.length) : 0;
  
  const trendData = [
    { month: "Jan", progress: Math.max(0, avgProgress - 30) },
    { month: "Feb", progress: Math.max(0, avgProgress - 20) },
    { month: "Mar", progress: Math.max(0, avgProgress - 10) },
    { month: "Apr", progress: Math.max(0, avgProgress - 5) },
    { month: "May", progress: avgProgress },
  ];

  return (
    <Layout role="manager">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          #print-area, #print-area * { visibility: visible; }
          #print-area { position: absolute; left: 0; top: 0; width: 100%; padding: 0; }
          aside, header { display: none !important; }
        }
      `}</style>

      <PageEnter className="space-y-6 max-w-7xl mx-auto w-full pb-12">
        <PageHeader
          tone="primary"
          icon={<BarChart3 className="w-7 h-7 text-primary" />}
          title="Team Reports"
          description="Track team capability growth, engagement trends, and applied AI impact."
          actions={
            <Button variant="outline" onClick={() => window.print()}>
              <Printer className="w-4 h-4 me-2" /> Print / PDF
            </Button>
          }
        />

        <div id="print-area" className="space-y-8">
          <div className="print:block hidden mb-8">
            <h1 className="text-3xl font-bold text-foreground">Team Department Report</h1>
            <p className="text-muted-foreground mt-2">Generated by Line Manager • FAHR Federal AI Learning Platform</p>
          </div>

          <Stagger className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <StaggerItem as="div">
              <Card className="h-full">
                <CardContent className="p-6 flex flex-col justify-center">
                  <div className="flex justify-between items-start mb-4">
                    <Activity className="w-5 h-5 text-muted-foreground" />
                  </div>
                  <p className="text-3xl font-bold text-foreground">{avgProgress}%</p>
                  <p className="text-sm text-muted-foreground mt-1">Avg. Pathway Completion</p>
                </CardContent>
              </Card>
            </StaggerItem>
            <StaggerItem as="div">
              <Card className="h-full bg-primary/5 border-primary/20">
                <CardContent className="p-6 flex flex-col justify-center">
                  <div className="flex justify-between items-start mb-4">
                    <TrendingUp className="w-5 h-5 text-primary" />
                  </div>
                  <p className="text-3xl font-bold text-primary">{hoursSaved}</p>
                  <p className="text-sm text-muted-foreground mt-1">Hours Saved / Month</p>
                </CardContent>
              </Card>
            </StaggerItem>
            <StaggerItem as="div">
              <Card className="h-full bg-primary/5 border-primary/20">
                <CardContent className="p-6 flex flex-col justify-center">
                  <div className="flex justify-between items-start mb-4">
                    <TrendingUp className="w-5 h-5 text-primary" />
                  </div>
                  <p className="text-3xl font-bold text-primary">{valueCreated.toLocaleString()} <span className="text-lg">AED</span></p>
                  <p className="text-sm text-muted-foreground mt-1">Est. Value Created (Annual)</p>
                </CardContent>
              </Card>
            </StaggerItem>
          </Stagger>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Capability Distribution</CardTitle>
                <CardDescription>Spread across the unified capability ladder</CardDescription>
              </CardHeader>
              <CardContent className="h-[300px]">
                <ChartReveal direction="rise" className="h-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={capabilityDistribution} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="name" fontSize={12} tickLine={false} axisLine={false} />
                      <YAxis fontSize={12} tickLine={false} axisLine={false} allowDecimals={false} />
                      <Tooltip cursor={{ fill: 'hsl(var(--muted)/0.5)' }} />
                      <Bar dataKey="count" radius={[4, 4, 0, 0]}>
                        {capabilityDistribution.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={entry.fill} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </ChartReveal>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Pathway Progress Trend</CardTitle>
                <CardDescription>Average pathway completion over time</CardDescription>
              </CardHeader>
              <CardContent className="h-[300px]">
                <ChartReveal direction="rise" className="h-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <AreaChart data={trendData} margin={{ top: 10, right: 10, left: -20, bottom: 20 }}>
                      <defs>
                        <linearGradient id="colorProgress" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="hsl(var(--primary))" stopOpacity={0.3}/>
                          <stop offset="95%" stopColor="hsl(var(--primary))" stopOpacity={0}/>
                        </linearGradient>
                      </defs>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} />
                      <XAxis dataKey="month" fontSize={12} tickLine={false} axisLine={false} />
                      <YAxis fontSize={12} tickLine={false} axisLine={false} domain={[0, 100]} />
                      <Tooltip />
                      <Area type="monotone" dataKey="progress" stroke="hsl(var(--primary))" fillOpacity={1} fill="url(#colorProgress)" />
                    </AreaChart>
                  </ResponsiveContainer>
                </ChartReveal>
              </CardContent>
            </Card>
          </div>
          
          <div className="print:block hidden text-xs text-muted-foreground pt-8 border-t border-border">
            Federal Agentic AI Learning & Skilling Platform • Official Document
          </div>
        </div>
      </PageEnter>
    </Layout>
  );
}
