// Authored seed for the federal programme model.
//
// Only ministry-level headline figures, department shares and the demo roster
// are authored here. Department rows, ministry roll-ups and every federal total
// are derived in `selectors.ts`, so a number can only be changed in one place.

import { LEARNER_PROFILE } from "@/lib/constants";
import type {
  ApprovalRecord,
  AuditEvent,
  Cohort,
  ContentItem,
  Credential,
  Escalation,
  GovernancePolicy,
  Ministry,
  Person,
  PlatformUser,
  ScheduledSession,
  Submission,
} from "./model";

/** The entity, manager and learner the demo is played as. */
export const FOCUS = {
  ministryId: "mohap",
  departmentId: "mohap-comms",
  managerId: "p-mariam",
  /** Aisha — her figures come from the live learner journey, not the seed. */
  learnerId: "p-aisha",
} as const;

/**
 * Fourteen federal entities. Employees sum to 80,000, active learners to
 * 41,850 and the employee-weighted readiness mean rounds to 64 — the figures
 * the leadership and FAHR views headline.
 */
export const MINISTRIES: Ministry[] = [
  {
    id: "mohap",
    name: "Ministry of Health and Prevention",
    shortName: "Health",
    employees: 4820,
    activeLearners: 3940,
    readiness: 68,
    twins: 1245,
    projectsSubmitted: 318,
    valueCreatedAedM: 4.2,
    hoursSavedPerMonth: 9850,
    credentialsIssued: 1180,
    topGapCompetencyId: "agentic",
    entityAdmin: "Noura Al Kaabi",
    tokensUsedM: 4.2,
    tokenQuotaM: 5.0,
  },
  {
    id: "moe",
    name: "Ministry of Education",
    shortName: "Education",
    employees: 12500,
    activeLearners: 8200,
    readiness: 71,
    twins: 3400,
    projectsSubmitted: 840,
    valueCreatedAedM: 12.0,
    hoursSavedPerMonth: 18900,
    credentialsIssued: 2460,
    topGapCompetencyId: "prompting",
    entityAdmin: "Ahmed Al Shamsi",
    tokensUsedM: 8.1,
    tokenQuotaM: 10.0,
  },
  {
    id: "econ",
    name: "Ministry of Economy",
    shortName: "Economy",
    employees: 2100,
    activeLearners: 1850,
    readiness: 82,
    twins: 1100,
    projectsSubmitted: 420,
    valueCreatedAedM: 8.5,
    hoursSavedPerMonth: 5600,
    credentialsIssued: 740,
    topGapCompetencyId: "analytics",
    entityAdmin: "Latifa Al Marzooqi",
    tokensUsedM: 2.9,
    tokenQuotaM: 3.0,
  },
  {
    id: "mohre",
    name: "Ministry of Human Resources and Emiratisation",
    shortName: "Human Resources",
    employees: 3400,
    activeLearners: 2900,
    readiness: 75,
    twins: 1650,
    projectsSubmitted: 380,
    valueCreatedAedM: 6.1,
    hoursSavedPerMonth: 7400,
    credentialsIssued: 980,
    topGapCompetencyId: "agentic",
    entityAdmin: "Hamad Al Falasi",
    tokensUsedM: 1.5,
    tokenQuotaM: 4.0,
  },
  {
    id: "moccae",
    name: "Ministry of Climate Change and Environment",
    shortName: "Climate Change",
    employees: 2600,
    activeLearners: 1700,
    readiness: 66,
    twins: 520,
    projectsSubmitted: 120,
    valueCreatedAedM: 2.6,
    hoursSavedPerMonth: 3600,
    credentialsIssued: 430,
    topGapCompetencyId: "analytics",
    entityAdmin: "Shamma Al Hosani",
    tokensUsedM: 2.1,
    tokenQuotaM: 2.0,
  },
  {
    id: "moei",
    name: "Ministry of Energy and Infrastructure",
    shortName: "Energy",
    employees: 3900,
    activeLearners: 2300,
    readiness: 65,
    twins: 690,
    projectsSubmitted: 165,
    valueCreatedAedM: 4.4,
    hoursSavedPerMonth: 5100,
    credentialsIssued: 560,
    topGapCompetencyId: "agentic",
    entityAdmin: "Rashid Al Muhairi",
    tokensUsedM: 1.8,
    tokenQuotaM: 3.0,
  },
  {
    id: "moiat",
    name: "Ministry of Industry and Advanced Technology",
    shortName: "Industry",
    employees: 1800,
    activeLearners: 1250,
    readiness: 70,
    twins: 480,
    projectsSubmitted: 110,
    valueCreatedAedM: 3.1,
    hoursSavedPerMonth: 2900,
    credentialsIssued: 340,
    topGapCompetencyId: "governance",
    entityAdmin: "Maitha Al Suwaidi",
    tokensUsedM: 1.2,
    tokenQuotaM: 2.0,
  },
  {
    id: "dgov",
    name: "Ministry of Digital Economy and AI",
    shortName: "Digital Economy",
    employees: 1200,
    activeLearners: 1080,
    readiness: 88,
    twins: 620,
    projectsSubmitted: 190,
    valueCreatedAedM: 6.8,
    hoursSavedPerMonth: 4200,
    credentialsIssued: 520,
    topGapCompetencyId: "governance",
    entityAdmin: "Sultan Al Neyadi",
    tokensUsedM: 2.4,
    tokenQuotaM: 3.0,
  },
  {
    id: "mofa",
    name: "Ministry of Foreign Affairs",
    shortName: "Foreign Affairs",
    employees: 4200,
    activeLearners: 2150,
    readiness: 63,
    twins: 640,
    projectsSubmitted: 140,
    valueCreatedAedM: 2.9,
    hoursSavedPerMonth: 4400,
    credentialsIssued: 480,
    topGapCompetencyId: "prompting",
    entityAdmin: "Khalifa Al Mansouri",
    tokensUsedM: 1.6,
    tokenQuotaM: 2.5,
  },
  {
    id: "moi",
    name: "Ministry of Interior",
    shortName: "Interior",
    employees: 18000,
    activeLearners: 6300,
    readiness: 58,
    twins: 1900,
    projectsSubmitted: 380,
    valueCreatedAedM: 7.5,
    hoursSavedPerMonth: 12600,
    credentialsIssued: 1240,
    topGapCompetencyId: "literacy",
    entityAdmin: "Obaid Al Ketbi",
    tokensUsedM: 3.4,
    tokenQuotaM: 6.0,
  },
  {
    id: "moj",
    name: "Ministry of Justice",
    shortName: "Justice",
    employees: 3600,
    activeLearners: 1480,
    readiness: 55,
    twins: 380,
    projectsSubmitted: 95,
    valueCreatedAedM: 1.9,
    hoursSavedPerMonth: 2700,
    credentialsIssued: 310,
    topGapCompetencyId: "governance",
    entityAdmin: "Salem Al Dhaheri",
    tokensUsedM: 0.9,
    tokenQuotaM: 2.0,
  },
  {
    id: "mocd",
    name: "Ministry of Community Development",
    shortName: "Community",
    employees: 2900,
    activeLearners: 1300,
    readiness: 61,
    twins: 350,
    projectsSubmitted: 90,
    valueCreatedAedM: 1.7,
    hoursSavedPerMonth: 2500,
    credentialsIssued: 280,
    topGapCompetencyId: "analytics",
    entityAdmin: "Amal Al Qubaisi",
    tokensUsedM: 0.8,
    tokenQuotaM: 1.5,
  },
  {
    id: "mccy",
    name: "Ministry of Culture and Youth",
    shortName: "Culture & Youth",
    employees: 2180,
    activeLearners: 1200,
    readiness: 65,
    twins: 320,
    projectsSubmitted: 102,
    valueCreatedAedM: 1.4,
    hoursSavedPerMonth: 2300,
    credentialsIssued: 260,
    topGapCompetencyId: "prompting",
    entityAdmin: "Reem Al Hashimi",
    tokensUsedM: 0.7,
    tokenQuotaM: 1.5,
  },
  {
    id: "mof",
    name: "Ministry of Finance",
    shortName: "Finance",
    employees: 16800,
    activeLearners: 6200,
    readiness: 61,
    twins: 1325,
    projectsSubmitted: 130,
    valueCreatedAedM: 8.9,
    hoursSavedPerMonth: 11800,
    credentialsIssued: 1150,
    topGapCompetencyId: "analytics",
    entityAdmin: "Younis Al Khoori",
    tokensUsedM: 3.1,
    tokenQuotaM: 5.0,
  },
];

export type DepartmentSeed = {
  /** Suffix of the generated department id (`<ministryId>-<id>`). */
  id: string;
  name: string;
  /** Share of the ministry's employees. */
  employeeWeight: number;
  /** Share of the ministry's active learners. */
  learnerWeight: number;
  /** Readiness relative to the ministry index; normalised so the mean holds. */
  readinessOffset: number;
};

/**
 * Department shares per ministry. Weights are absolute head counts for the
 * focus entity and proportional elsewhere — either way the generator makes
 * them sum to the ministry total exactly.
 */
export const DEPARTMENT_SEEDS: Record<string, DepartmentSeed[]> = {
  mohap: [
    { id: "comms", name: "Comms & Public Awareness", employeeWeight: 120, learnerWeight: 115, readinessOffset: 14 },
    { id: "happiness", name: "Customer Happiness", employeeWeight: 340, learnerWeight: 290, readinessOffset: 7 },
    { id: "hr", name: "HR & Training", employeeWeight: 85, learnerWeight: 80, readinessOffset: 3 },
    { id: "digital", name: "Digital Health", employeeWeight: 150, learnerWeight: 140, readinessOffset: 20 },
    { id: "preventive", name: "Preventive Medicine", employeeWeight: 620, learnerWeight: 520, readinessOffset: -2 },
    { id: "hospitals", name: "Hospitals & Clinics", employeeWeight: 2400, learnerWeight: 1950, readinessOffset: 2 },
    { id: "policy", name: "Health Policy & Licensing", employeeWeight: 700, learnerWeight: 570, readinessOffset: -6 },
    { id: "support", name: "Support Services & Procurement", employeeWeight: 405, learnerWeight: 275, readinessOffset: -16 },
  ],
  moe: [
    { id: "schools", name: "Schools Operations", employeeWeight: 7200, learnerWeight: 4300, readinessOffset: -4 },
    { id: "curriculum", name: "Curriculum & Assessment", employeeWeight: 2100, learnerWeight: 1700, readinessOffset: 6 },
    { id: "higher", name: "Higher Education Policy", employeeWeight: 1400, learnerWeight: 1100, readinessOffset: 3 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 1800, learnerWeight: 1100, readinessOffset: -3 },
  ],
  econ: [
    { id: "investment", name: "Investment Promotion", employeeWeight: 620, learnerWeight: 560, readinessOffset: 5 },
    { id: "sme", name: "Entrepreneurship & SMEs", employeeWeight: 480, learnerWeight: 430, readinessOffset: 2 },
    { id: "trade", name: "Trade & Competitiveness", employeeWeight: 560, learnerWeight: 500, readinessOffset: -2 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 440, learnerWeight: 360, readinessOffset: -6 },
  ],
  mohre: [
    { id: "labour", name: "Labour Relations", employeeWeight: 1200, learnerWeight: 1050, readinessOffset: -3 },
    { id: "emiratisation", name: "Emiratisation Programmes", employeeWeight: 900, learnerWeight: 800, readinessOffset: 6 },
    { id: "centres", name: "Customer Happiness Centres", employeeWeight: 800, learnerWeight: 680, readinessOffset: 1 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 500, learnerWeight: 370, readinessOffset: -5 },
  ],
  moccae: [
    { id: "climate", name: "Climate Policy", employeeWeight: 620, learnerWeight: 470, readinessOffset: 7 },
    { id: "food", name: "Food Diversity", employeeWeight: 900, learnerWeight: 560, readinessOffset: -4 },
    { id: "water", name: "Environment & Water", employeeWeight: 780, learnerWeight: 500, readinessOffset: 2 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 300, learnerWeight: 170, readinessOffset: -6 },
  ],
  moei: [
    { id: "transition", name: "Energy Transition", employeeWeight: 900, learnerWeight: 620, readinessOffset: 6 },
    { id: "infrastructure", name: "Infrastructure & Transport", employeeWeight: 1600, learnerWeight: 880, readinessOffset: -4 },
    { id: "housing", name: "Housing Programmes", employeeWeight: 800, learnerWeight: 480, readinessOffset: 1 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 600, learnerWeight: 320, readinessOffset: -3 },
  ],
  moiat: [
    { id: "advanced", name: "Advanced Technology", employeeWeight: 520, learnerWeight: 430, readinessOffset: 9 },
    { id: "industrial", name: "Industrial Development", employeeWeight: 640, learnerWeight: 430, readinessOffset: -3 },
    { id: "standards", name: "Standards & Metrology", employeeWeight: 380, learnerWeight: 250, readinessOffset: -2 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 260, learnerWeight: 140, readinessOffset: -6 },
  ],
  dgov: [
    { id: "policy", name: "AI & Digital Policy", employeeWeight: 380, learnerWeight: 360, readinessOffset: 5 },
    { id: "platforms", name: "Data & Platforms", employeeWeight: 340, learnerWeight: 320, readinessOffset: 3 },
    { id: "services", name: "Government Services", employeeWeight: 300, learnerWeight: 270, readinessOffset: -3 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 180, learnerWeight: 130, readinessOffset: -7 },
  ],
  mofa: [
    { id: "missions", name: "Diplomatic Missions Support", employeeWeight: 1800, learnerWeight: 850, readinessOffset: -4 },
    { id: "consular", name: "Consular Services", employeeWeight: 1100, learnerWeight: 620, readinessOffset: 3 },
    { id: "protocol", name: "Protocol & Communications", employeeWeight: 700, learnerWeight: 400, readinessOffset: 5 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 600, learnerWeight: 280, readinessOffset: -5 },
  ],
  moi: [
    { id: "police", name: "Federal Police Operations", employeeWeight: 9800, learnerWeight: 3100, readinessOffset: -5 },
    { id: "civil", name: "Civil Defence", employeeWeight: 3400, learnerWeight: 1200, readinessOffset: -2 },
    { id: "traffic", name: "Traffic & Licensing", employeeWeight: 2900, learnerWeight: 1300, readinessOffset: 7 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 1900, learnerWeight: 700, readinessOffset: 2 },
  ],
  moj: [
    { id: "courts", name: "Courts Administration", employeeWeight: 1700, learnerWeight: 640, readinessOffset: -4 },
    { id: "prosecution", name: "Public Prosecution Support", employeeWeight: 900, learnerWeight: 380, readinessOffset: 2 },
    { id: "notary", name: "Notary Services", employeeWeight: 600, learnerWeight: 290, readinessOffset: 6 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 400, learnerWeight: 170, readinessOffset: -3 },
  ],
  mocd: [
    { id: "care", name: "Social Care", employeeWeight: 1300, learnerWeight: 520, readinessOffset: -4 },
    { id: "empowerment", name: "Community Empowerment", employeeWeight: 700, learnerWeight: 340, readinessOffset: 5 },
    { id: "registry", name: "Social Registry", employeeWeight: 500, learnerWeight: 260, readinessOffset: 3 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 400, learnerWeight: 180, readinessOffset: -2 },
  ],
  mccy: [
    { id: "arts", name: "Culture & Arts", employeeWeight: 700, learnerWeight: 380, readinessOffset: 4 },
    { id: "youth", name: "Youth Programmes", employeeWeight: 620, learnerWeight: 380, readinessOffset: 6 },
    { id: "heritage", name: "Heritage", employeeWeight: 500, learnerWeight: 250, readinessOffset: -6 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 360, learnerWeight: 190, readinessOffset: -3 },
  ],
  mof: [
    { id: "budget", name: "Budget & Revenue", employeeWeight: 4200, learnerWeight: 1800, readinessOffset: 4 },
    { id: "systems", name: "Government Financial Systems", employeeWeight: 5600, learnerWeight: 2100, readinessOffset: -3 },
    { id: "procurement", name: "Procurement & Contracts", employeeWeight: 4300, learnerWeight: 1500, readinessOffset: -2 },
    { id: "corporate", name: "Corporate Services", employeeWeight: 2700, learnerWeight: 800, readinessOffset: 3 },
  ],
};

/**
 * National capability distribution. Counts sum to the federal active-learner
 * total, so the leadership band and the FAHR roll-up cannot disagree.
 * Keyed by capability-ladder id from `constants.ts`.
 */
export const CAPABILITY_DISTRIBUTION: Record<string, number> = {
  aware: 8420,
  emerging: 12555,
  practitioner: 14610,
  advanced: 5025,
  champion: 1240,
};

/** Quarterly national readiness against plan, for the leadership trajectory. */
export const READINESS_TRAJECTORY = [
  { quarter: "Q3 2025", readiness: 41, target: 50 },
  { quarter: "Q4 2025", readiness: 48, target: 55 },
  { quarter: "Q1 2026", readiness: 55, target: 60 },
  { quarter: "Q2 2026", readiness: 59, target: 65 },
  { quarter: "Q3 2026", readiness: 64, target: 70 },
];

/** Federal readiness target the trajectory is measured against. */
export const NATIONAL_TARGET = { readiness: 75, by: "Q2 2027" } as const;

/** Direction of travel per capability gap, used by the national risk view. */
export const GAP_TRENDS: Record<string, "rising" | "stable" | "declining"> = {
  literacy: "declining",
  prompting: "stable",
  analytics: "stable",
  agentic: "rising",
  governance: "declining",
};

/** Digital-twin adoption for the focus entity, month by month. */
export const TWIN_ADOPTION = [
  { month: "Jan", twins: 120 },
  { month: "Feb", twins: 340 },
  { month: "Mar", twins: 680 },
  { month: "Apr", twins: 950 },
  { month: "May", twins: 1245 },
];

/**
 * Cohorts. The focus entity's twelve cohorts account for every one of its
 * 3,940 active learners, so the cohort screen reconciles with the dashboard.
 */
export const COHORTS: Cohort[] = [
  { id: "mohap-c1", ministryId: "mohap", name: "Executive Leadership Batch 2", status: "Active", learners: 45, progress: 75, startsOn: "2 March 2026" },
  { id: "mohap-c2", ministryId: "mohap", departmentId: "mohap-happiness", name: "Customer Happiness Agents", status: "Onboarding", learners: 290, progress: 15, startsOn: "6 July 2026" },
  { id: "mohap-c3", ministryId: "mohap", departmentId: "mohap-digital", name: "Data Analytics Champions", status: "Active", learners: 120, progress: 55, startsOn: "13 April 2026" },
  { id: "mohap-c4", ministryId: "mohap", departmentId: "mohap-hr", name: "HR Automation Team", status: "Completed", learners: 80, progress: 100, startsOn: "12 January 2026" },
  { id: "mohap-c5", ministryId: "mohap", departmentId: "mohap-comms", name: "Comms & Marketing Batch 1", status: "Active", learners: 115, progress: 46, startsOn: "4 May 2026" },
  { id: "mohap-c6", ministryId: "mohap", departmentId: "mohap-hospitals", name: "Clinical Operations Wave 1", status: "Active", learners: 780, progress: 48, startsOn: "9 February 2026" },
  { id: "mohap-c7", ministryId: "mohap", departmentId: "mohap-hospitals", name: "Clinical Operations Wave 2", status: "Onboarding", learners: 620, progress: 12, startsOn: "13 July 2026" },
  { id: "mohap-c8", ministryId: "mohap", departmentId: "mohap-hospitals", name: "Clinical Operations Wave 3", status: "Planning", learners: 450, progress: 0, startsOn: "5 October 2026" },
  { id: "mohap-c9", ministryId: "mohap", departmentId: "mohap-preventive", name: "Preventive Medicine Cohort", status: "Active", learners: 520, progress: 41, startsOn: "16 March 2026" },
  { id: "mohap-c10", ministryId: "mohap", departmentId: "mohap-policy", name: "Health Policy & Licensing Cohort", status: "Active", learners: 570, progress: 36, startsOn: "20 April 2026" },
  { id: "mohap-c11", ministryId: "mohap", departmentId: "mohap-digital", name: "Digital Health Innovators", status: "Active", learners: 140, progress: 68, startsOn: "19 January 2026" },
  { id: "mohap-c12", ministryId: "mohap", departmentId: "mohap-support", name: "Support Services Uplift", status: "Onboarding", learners: 210, progress: 22, startsOn: "1 June 2026" },
  { id: "moe-c1", ministryId: "moe", departmentId: "moe-curriculum", name: "Curriculum AI Design Cohort", status: "Active", learners: 640, progress: 58, startsOn: "23 February 2026" },
  { id: "econ-c1", ministryId: "econ", departmentId: "econ-investment", name: "Investment Insight Cohort", status: "Active", learners: 210, progress: 72, startsOn: "16 February 2026" },
  { id: "moi-c1", ministryId: "moi", departmentId: "moi-traffic", name: "Traffic Services Wave 1", status: "Active", learners: 480, progress: 34, startsOn: "11 May 2026" },
  { id: "mof-c1", ministryId: "mof", departmentId: "mof-budget", name: "Finance Automation Cohort", status: "Onboarding", learners: 360, progress: 18, startsOn: "29 June 2026" },
];

/**
 * The authored roster. Everyone the demo can drill into by name lives here;
 * departments without authored people synthesise a consistent roster instead.
 */
export const PEOPLE: Person[] = [
  {
    id: "p-mariam",
    name: "Mariam Al Zaabi",
    role: "Director of Communications & Public Awareness",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c1",
    isManager: true,
    levelId: "advanced",
    pathwayProgress: 88,
    assessmentScore: 90,
    lastActive: "20 mins ago",
    status: "excelling",
  },
  {
    id: "p-aisha",
    name: LEARNER_PROFILE.name,
    role: LEARNER_PROFILE.role,
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "practitioner",
    pathwayProgress: 43,
    assessmentScore: 78,
    lastActive: "2 hours ago",
    status: "on-track",
    live: true,
  },
  {
    id: "p-khalid-h",
    name: "Khalid Al Hashimi",
    role: "Operations Specialist",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "aware",
    pathwayProgress: 20,
    assessmentScore: 38,
    lastActive: "14 days ago",
    status: "at-risk",
    competencyScores: { literacy: 45, prompting: 35, analytics: 30, agentic: 25, governance: 55 },
    gapCompetencyIds: ["agentic", "analytics", "prompting"],
  },
  {
    id: "p-fatima-q",
    name: "Fatima Al Qasimi",
    role: "Service Designer",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "emerging",
    pathwayProgress: 60,
    assessmentScore: 62,
    lastActive: "1 day ago",
    status: "on-track",
    competencyScores: { literacy: 72, prompting: 68, analytics: 55, agentic: 48, governance: 65 },
    gapCompetencyIds: ["agentic", "analytics"],
  },
  {
    id: "p-omar",
    name: "Omar Tariq",
    role: "Data Engineer",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "advanced",
    pathwayProgress: 95,
    assessmentScore: 91,
    lastActive: "5 mins ago",
    status: "excelling",
    competencyScores: { literacy: 95, prompting: 88, analytics: 96, agentic: 90, governance: 84 },
    gapCompetencyIds: ["governance"],
  },
  {
    id: "p-zayed",
    name: "Zayed Al Marri",
    role: "HR Coordinator",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "emerging",
    pathwayProgress: 45,
    assessmentScore: 55,
    lastActive: "3 days ago",
    status: "needs-attention",
    competencyScores: { literacy: 65, prompting: 58, analytics: 45, agentic: 40, governance: 62 },
    gapCompetencyIds: ["agentic", "analytics", "prompting"],
  },
  {
    id: "p-noura-s",
    name: "Noura Al Suwaidi",
    role: "Content Producer",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    managerId: "p-mariam",
    levelId: "practitioner",
    pathwayProgress: 72,
    assessmentScore: 74,
    lastActive: "Yesterday",
    status: "on-track",
    competencyScores: { literacy: 82, prompting: 86, analytics: 62, agentic: 58, governance: 78 },
    gapCompetencyIds: ["agentic", "analytics"],
  },
  {
    id: "p-saeed",
    name: "Saeed Al Balushi",
    role: "Customer Support Lead",
    ministryId: "mohap",
    departmentId: "mohap-happiness",
    cohortId: "mohap-c2",
    levelId: "advanced",
    pathwayProgress: 84,
    assessmentScore: 92,
    lastActive: "1 hour ago",
    status: "excelling",
  },
  {
    id: "p-fatima-z",
    name: "Fatima Al Zaabi",
    role: "HR Specialist",
    ministryId: "mohap",
    departmentId: "mohap-hr",
    cohortId: "mohap-c4",
    levelId: "emerging",
    pathwayProgress: 52,
    assessmentScore: 65,
    lastActive: "2 days ago",
    status: "needs-attention",
  },
  {
    id: "p-khalid-r",
    name: "Khalid Al Rashid",
    role: "Data Analyst",
    ministryId: "mohap",
    departmentId: "mohap-digital",
    cohortId: "mohap-c11",
    levelId: "champion",
    pathwayProgress: 96,
    assessmentScore: 98,
    lastActive: "30 mins ago",
    status: "excelling",
  },
  {
    id: "p-hessa",
    name: "Hessa Al Nuaimi",
    role: "Clinical Operations Lead",
    ministryId: "mohap",
    departmentId: "mohap-hospitals",
    cohortId: "mohap-c6",
    levelId: "practitioner",
    pathwayProgress: 66,
    assessmentScore: 72,
    lastActive: "4 hours ago",
    status: "on-track",
  },
  {
    id: "p-yousef",
    name: "Yousef Al Ali",
    role: "Licensing Officer",
    ministryId: "mohap",
    departmentId: "mohap-policy",
    cohortId: "mohap-c10",
    levelId: "emerging",
    pathwayProgress: 38,
    assessmentScore: 58,
    lastActive: "6 days ago",
    status: "needs-attention",
  },
  {
    id: "p-alia",
    name: "Alia Al Blooshi",
    role: "Curriculum Designer",
    ministryId: "moe",
    departmentId: "moe-curriculum",
    cohortId: "moe-c1",
    levelId: "advanced",
    pathwayProgress: 81,
    assessmentScore: 88,
    lastActive: "3 hours ago",
    status: "excelling",
  },
  {
    id: "p-tariq",
    name: "Tariq Al Ameri",
    role: "Investment Analyst",
    ministryId: "econ",
    departmentId: "econ-investment",
    cohortId: "econ-c1",
    levelId: "champion",
    pathwayProgress: 92,
    assessmentScore: 94,
    lastActive: "Yesterday",
    status: "excelling",
  },
  {
    id: "p-sara",
    name: "Sara Al Mazrouei",
    role: "Licensing Supervisor",
    ministryId: "moi",
    departmentId: "moi-traffic",
    cohortId: "moi-c1",
    levelId: "practitioner",
    pathwayProgress: 57,
    assessmentScore: 69,
    lastActive: "2 days ago",
    status: "on-track",
  },
];

/**
 * Workplace-project submissions across the approval chain. The focus entity
 * has one waiting on the manager (Aisha's), one already with the entity, one
 * sent back for revision and three live in service.
 */
export const SUBMISSIONS: Submission[] = [
  {
    id: "s1",
    title: "AI-Assisted Public Health Campaign Brief Generator",
    personId: "p-aisha",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    state: "awaiting_manager",
    impact: "High",
    governanceStatus: "Compliant",
    reviewer: "Mariam Al Zaabi",
    description:
      "Generates tailored health campaign briefs from historical public health data and demographic models, cutting the time from request to approved brief.",
    metrics: "Expected to save 40 hours per campaign. Projected cost reduction: AED 15,000 per month.",
    estimatedValueAed: 180000,
    hoursSavedPerMonth: 40,
    competencyIds: ["prompting", "agentic", "governance"],
    submittedOn: "22 July 2026",
    timeline: [
      { date: "19 July 2026", event: "Drafted with the AI Practice Partner" },
      { date: "22 July 2026", event: "Submitted for department manager sign-off" },
    ],
  },
  {
    id: "s2",
    title: "Clinic FAQ AI Assistant",
    personId: "p-saeed",
    ministryId: "mohap",
    departmentId: "mohap-happiness",
    cohortId: "mohap-c2",
    state: "endorsed",
    impact: "Medium",
    governanceStatus: "Compliant",
    reviewer: "Noura Al Kaabi",
    description:
      "An internal digital twin trained on clinical standard operating procedures that answers front-desk queries instantly.",
    metrics: "Reduced average handling time by 35%. 98% accuracy in the pilot.",
    estimatedValueAed: 240000,
    hoursSavedPerMonth: 120,
    competencyIds: ["agentic", "governance"],
    submittedOn: "9 June 2026",
    timeline: [
      { date: "4 June 2026", event: "Prototype completed" },
      { date: "9 June 2026", event: "Department manager signed off" },
      { date: "14 June 2026", event: "Entity endorsed for pilot" },
    ],
  },
  {
    id: "s3",
    title: "Vaccination Campaign Content Automation",
    personId: "p-noura-s",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    state: "deployed",
    impact: "High",
    governanceStatus: "Compliant",
    reviewer: "Noura Al Kaabi",
    description:
      "Automated generation of bilingual social media posts and press releases for national vaccination drives.",
    metrics: "Content production time reduced from 3 days to 4 hours.",
    estimatedValueAed: 420000,
    hoursSavedPerMonth: 96,
    competencyIds: ["prompting", "agentic"],
    submittedOn: "4 May 2026",
    timeline: [
      { date: "4 May 2026", event: "Submitted for department manager sign-off" },
      { date: "11 May 2026", event: "Department manager signed off" },
      { date: "2 June 2026", event: "Entity endorsed and deployed" },
    ],
  },
  {
    id: "s4",
    title: "Patient Feedback Summarisation Agent",
    personId: "p-khalid-r",
    ministryId: "mohap",
    departmentId: "mohap-digital",
    cohortId: "mohap-c11",
    state: "deployed",
    impact: "High",
    governanceStatus: "Compliant",
    reviewer: "Noura Al Kaabi",
    description:
      "Aggregates unstructured patient feedback from several channels and categorises it into actionable weekly reports.",
    metrics: "Weekly reporting effort down from 14 hours to 2. Sentiment coverage up from 20% to 100% of channels.",
    estimatedValueAed: 510000,
    hoursSavedPerMonth: 48,
    competencyIds: ["analytics", "agentic"],
    submittedOn: "3 April 2026",
    timeline: [
      { date: "3 April 2026", event: "Submitted for department manager sign-off" },
      { date: "9 April 2026", event: "Department manager signed off" },
      { date: "18 April 2026", event: "Entity endorsed and deployed" },
    ],
  },
  {
    id: "s5",
    title: "Clinical Rostering Assistant",
    personId: "p-hessa",
    ministryId: "mohap",
    departmentId: "mohap-hospitals",
    cohortId: "mohap-c6",
    state: "awaiting_entity",
    impact: "High",
    governanceStatus: "Needs Review",
    reviewer: "Noura Al Kaabi",
    description:
      "Drafts fortnightly clinical rosters against leave, skill mix and shift-fairness rules, leaving the final roster to a human planner.",
    metrics: "Roster preparation down from 11 hours to 90 minutes per fortnight across four hospitals.",
    estimatedValueAed: 620000,
    hoursSavedPerMonth: 76,
    competencyIds: ["agentic", "governance"],
    submittedOn: "14 July 2026",
    timeline: [
      { date: "14 July 2026", event: "Submitted for department manager sign-off" },
      { date: "20 July 2026", event: "Department manager signed off — sent for entity endorsement" },
    ],
  },
  {
    id: "s6",
    title: "Licensing Enquiry Triage Assistant",
    personId: "p-yousef",
    ministryId: "mohap",
    departmentId: "mohap-policy",
    cohortId: "mohap-c10",
    state: "revision_requested",
    impact: "Medium",
    governanceStatus: "Needs Review",
    reviewer: "Noura Al Kaabi",
    description:
      "Classifies inbound licensing enquiries and drafts a first response for an officer to check before it is sent.",
    metrics: "Pilot handled 62% of enquiries without escalation; response drafting time down 40%.",
    estimatedValueAed: 150000,
    hoursSavedPerMonth: 34,
    competencyIds: ["prompting", "governance"],
    submittedOn: "2 July 2026",
    timeline: [
      { date: "2 July 2026", event: "Submitted for department manager sign-off" },
      { date: "8 July 2026", event: "Revision requested — evidence of human review missing" },
    ],
  },
  {
    id: "s7",
    title: "Pharmacy Inspection Report Copilot",
    personId: "p-fatima-q",
    ministryId: "mohap",
    departmentId: "mohap-comms",
    cohortId: "mohap-c5",
    state: "awaiting_manager",
    impact: "Medium",
    governanceStatus: "Compliant",
    reviewer: "Mariam Al Zaabi",
    description:
      "Turns inspection field notes into a structured report with flagged findings, ready for the inspector to confirm.",
    metrics: "Report turnaround down from 2 days to 3 hours in a six-inspector pilot.",
    estimatedValueAed: 130000,
    hoursSavedPerMonth: 28,
    competencyIds: ["prompting", "agentic"],
    submittedOn: "24 July 2026",
    timeline: [
      { date: "21 July 2026", event: "Drafted with the AI Practice Partner" },
      { date: "24 July 2026", event: "Submitted for department manager sign-off" },
    ],
  },
  {
    id: "s8",
    title: "Curriculum Feedback Synthesiser",
    personId: "p-alia",
    ministryId: "moe",
    departmentId: "moe-curriculum",
    cohortId: "moe-c1",
    state: "escalated",
    impact: "High",
    governanceStatus: "Needs Review",
    reviewer: "FAHR Programme Team",
    description:
      "Synthesises teacher and parent feedback into curriculum revision recommendations across all emirates.",
    metrics: "Covers 24,000 feedback records per term; recommendation drafting down from 5 weeks to 6 days.",
    estimatedValueAed: 1400000,
    hoursSavedPerMonth: 180,
    competencyIds: ["analytics", "governance"],
    submittedOn: "6 July 2026",
    timeline: [
      { date: "6 July 2026", event: "Submitted for department manager sign-off" },
      { date: "10 July 2026", event: "Department manager signed off" },
      { date: "15 July 2026", event: "Escalated to FAHR — federal data-sharing exception needed" },
    ],
  },
  {
    id: "s9",
    title: "Field Report Summariser",
    personId: "p-sara",
    ministryId: "moi",
    departmentId: "moi-traffic",
    cohortId: "moi-c1",
    state: "awaiting_entity",
    impact: "Medium",
    governanceStatus: "Compliant",
    reviewer: "Obaid Al Ketbi",
    description:
      "Summarises traffic incident field reports into a shift briefing, with the officer confirming every summary.",
    metrics: "Shift briefing preparation down from 70 to 20 minutes.",
    estimatedValueAed: 210000,
    hoursSavedPerMonth: 42,
    competencyIds: ["literacy", "prompting"],
    submittedOn: "13 July 2026",
    timeline: [
      { date: "13 July 2026", event: "Submitted for department manager sign-off" },
      { date: "21 July 2026", event: "Department manager signed off — sent for entity endorsement" },
    ],
  },
  {
    id: "s10",
    title: "Investor Briefing Generator",
    personId: "p-tariq",
    ministryId: "econ",
    departmentId: "econ-investment",
    cohortId: "econ-c1",
    state: "endorsed",
    impact: "High",
    governanceStatus: "Compliant",
    reviewer: "Latifa Al Marzooqi",
    description:
      "Builds investor-ready sector briefings from federal economic indicators, with an analyst approving every figure.",
    metrics: "Briefing preparation down from 3 days to 4 hours; 38 briefings produced in the pilot quarter.",
    estimatedValueAed: 890000,
    hoursSavedPerMonth: 110,
    competencyIds: ["analytics", "prompting"],
    submittedOn: "5 June 2026",
    timeline: [
      { date: "5 June 2026", event: "Submitted for department manager sign-off" },
      { date: "12 June 2026", event: "Department manager signed off" },
      { date: "17 June 2026", event: "Entity endorsed" },
    ],
  },
];

/** Decisions already taken before the demo starts. */
export const APPROVALS: ApprovalRecord[] = [
  { id: "a1", submissionId: "s2", role: "manager", decision: "signed_off", by: "Noura Al Kaabi", on: "9 June 2026" },
  { id: "a2", submissionId: "s2", role: "ministry", decision: "endorsed", by: "Noura Al Kaabi", on: "14 June 2026", note: "Approved for a six-clinic pilot." },
  { id: "a3", submissionId: "s3", role: "manager", decision: "signed_off", by: "Mariam Al Zaabi", on: "11 May 2026" },
  { id: "a4", submissionId: "s3", role: "ministry", decision: "endorsed", by: "Noura Al Kaabi", on: "2 June 2026" },
  { id: "a5", submissionId: "s4", role: "manager", decision: "signed_off", by: "Ali Al Hammadi", on: "9 April 2026" },
  { id: "a6", submissionId: "s4", role: "ministry", decision: "endorsed", by: "Noura Al Kaabi", on: "18 April 2026" },
  { id: "a7", submissionId: "s5", role: "manager", decision: "signed_off", by: "Ali Al Hammadi", on: "20 July 2026" },
  { id: "a8", submissionId: "s6", role: "manager", decision: "revision_requested", by: "Yousef Al Ali's department manager", on: "8 July 2026", note: "Add the human-review step before resubmitting." },
  { id: "a9", submissionId: "s8", role: "manager", decision: "signed_off", by: "Alia's department manager", on: "10 July 2026" },
  { id: "a10", submissionId: "s8", role: "ministry", decision: "escalated", by: "Ahmed Al Shamsi", on: "15 July 2026", note: "Federal data-sharing exception required." },
  { id: "a11", submissionId: "s9", role: "manager", decision: "signed_off", by: "Sara's department manager", on: "21 July 2026" },
  { id: "a12", submissionId: "s10", role: "manager", decision: "signed_off", by: "Tariq's department manager", on: "12 June 2026" },
  { id: "a13", submissionId: "s10", role: "ministry", decision: "endorsed", by: "Latifa Al Marzooqi", on: "17 June 2026" },
];

/** Seeded audit trail. Every action taken in the demo appends to this. */
export const AUDIT_EVENTS: AuditEvent[] = [
  { id: "ae1", time: "10 mins ago", actor: "Aisha Al Mansoori", agent: "Capability Agent", action: "Recommended Workplace Project", risk: "Low", status: "Approved", ministryId: "mohap" },
  { id: "ae2", time: "1 hour ago", actor: "Saeed Al Balushi", agent: "AI Practice Partner", action: "Reviewed Project", risk: "Medium", status: "Pending Human Review", ministryId: "mohap" },
  { id: "ae3", time: "2 hours ago", actor: "Noura Al Kaabi", agent: "Analytics Agent", action: "Generated Federal Report", risk: "Low", status: "Approved", ministryId: "mohap" },
  { id: "ae4", time: "Yesterday", actor: "System", agent: "Analytics Agent", action: "Flagged Data Policy Warning (PII)", risk: "High", status: "Blocked", ministryId: "moe" },
  { id: "ae5", time: "Yesterday", actor: "Khalid Al Rashid", agent: "Content Agent", action: "Connected Knowledge Source", risk: "Low", status: "Approved", ministryId: "mohap" },
  { id: "ae6", time: "2 days ago", actor: "Ahmed Al Shamsi", agent: "Human decision", action: "Escalated Curriculum Feedback Synthesiser to FAHR", risk: "Medium", status: "Open", ministryId: "moe" },
  { id: "ae7", time: "3 days ago", actor: "FAHR Programme Team", agent: "Human decision", action: "Raised Climate Change token quota to 2.0M", risk: "Low", status: "Applied", ministryId: "moccae" },
];

/** Instructor-led and virtual sessions administered by the entity and FAHR. */
export const SESSIONS: ScheduledSession[] = [
  { id: "ev1", title: "Masterclass: Agentic AI in Public Policy", mode: "Virtual", date: "20 August 2026", time: "10:00 – 12:00", host: "FAHR Programme Team", seats: 500, registered: 418, status: "Open" },
  { id: "ev2", title: "Prompt Craft Clinic for Communications Teams", mode: "Virtual", date: "27 August 2026", time: "13:00 – 14:30", host: "Mariam Al Zaabi", ministryId: "mohap", seats: 120, registered: 120, status: "Full" },
  { id: "ev3", title: "Responsible AI Review Workshop", mode: "In person", date: "3 September 2026", time: "09:00 – 15:00", host: "FAHR Governance Office", seats: 60, registered: 44, status: "Open" },
  { id: "ev4", title: "Clinical AI Assistants: Hands-on Lab", mode: "Hybrid", date: "2 June 2026", time: "09:30 – 12:30", host: "Digital Health", ministryId: "mohap", seats: 80, registered: 51, status: "Open" },
  { id: "ev5", title: "Entity Admin Onboarding: Cohorts & Reporting", mode: "Virtual", date: "14 July 2026", time: "11:00 – 12:00", host: "FAHR Programme Team", seats: 40, registered: 40, status: "Completed" },
  { id: "ev6", title: "Department Manager Briefing: Reading a Capability Profile", mode: "Virtual", date: "10 August 2026", time: "09:00 – 10:00", host: "Noura Al Kaabi", ministryId: "mohap", seats: 60, registered: 37, status: "Open" },
  { id: "ev7", title: "Customer Happiness Cohort Induction", mode: "Virtual", date: "18 August 2026", time: "13:00 – 14:00", host: "Saeed Al Balushi", ministryId: "mohap", seats: 300, registered: 214, status: "Open" },
  { id: "ev8", title: "HR Automation Team: Project Showcase", mode: "In person", date: "24 June 2026", time: "10:00 – 13:00", host: "Fatima Al Zaabi", ministryId: "mohap", seats: 90, registered: 74, status: "Completed" },
];

/** Catalogue items with competency mapping, version and publish state. */
export const CONTENT_ITEMS: ContentItem[] = [
  { id: "ct1", title: "AI Foundations for Federal Service", type: "Course", competencyId: "literacy", language: "Bilingual", version: "v3.1", status: "Published", updatedOn: "4 June 2026", owner: "FAHR Programme Team" },
  { id: "ct2", title: "Prompt Engineering for Public Service", type: "Course", competencyId: "prompting", language: "Bilingual", version: "v2.4", status: "Published", updatedOn: "18 June 2026", owner: "FAHR Programme Team" },
  { id: "ct3", title: "AI Governance & Data Ethics in Federal Work", type: "Course", competencyId: "governance", language: "Bilingual", version: "v2.0", status: "Published", updatedOn: "2 July 2026", owner: "FAHR Governance Office" },
  { id: "ct4", title: "Reading Service Data with AI", type: "Microlearning", competencyId: "analytics", language: "English", version: "v1.2", status: "Published", updatedOn: "21 July 2026", owner: "Digital Health" },
  { id: "ct5", title: "Designing Your First Agentic Workflow", type: "Simulation", competencyId: "agentic", language: "English", version: "v1.0", status: "In review", updatedOn: "13 July 2026", owner: "FAHR Programme Team" },
  { id: "ct6", title: "Stakeholder Alignment with AI", type: "Microlearning", competencyId: "prompting", language: "Bilingual", version: "v1.1", status: "Published", updatedOn: "19 July 2026", owner: "Comms & Public Awareness" },
  { id: "ct7", title: "Workplace Project Brief Template", type: "Assignment", competencyId: "agentic", language: "Bilingual", version: "v4.0", status: "Published", updatedOn: "17 June 2026", owner: "FAHR Programme Team" },
  { id: "ct8", title: "Human-in-the-loop Review Clinic", type: "Virtual session", competencyId: "governance", language: "Arabic", version: "v1.0", status: "Scheduled", updatedOn: "22 July 2026", owner: "FAHR Governance Office" },
];

/** Credentials already issued. Issuing one in the demo appends to this. */
export const CREDENTIALS: Credential[] = [
  { id: "cr1", personId: "p-omar", personName: "Omar Tariq", title: "Advanced Agentic AI Practitioner", levelId: "advanced", issuedOn: "12 June 2026", ministryId: "mohap", submissionId: "s3", verificationCode: "FAHR-2026-OT-4417" },
  { id: "cr2", personId: "p-khalid-r", personName: "Khalid Al Rashid", title: "AI Capability Champion", levelId: "champion", issuedOn: "20 July 2026", ministryId: "mohap", submissionId: "s4", verificationCode: "FAHR-2026-KR-2298" },
  { id: "cr3", personId: "p-saeed", personName: "Saeed Al Balushi", title: "Advanced Agentic AI Practitioner", levelId: "advanced", issuedOn: "11 July 2026", ministryId: "mohap", submissionId: "s2", verificationCode: "FAHR-2026-SB-7731" },
  { id: "cr4", personId: "p-tariq", personName: "Tariq Al Ameri", title: "AI Capability Champion", levelId: "champion", issuedOn: "6 July 2026", ministryId: "econ", submissionId: "s10", verificationCode: "FAHR-2026-TA-1043" },
  { id: "cr5", personId: "p-mariam", personName: "Mariam Al Zaabi", title: "Advanced Agentic AI Practitioner", levelId: "advanced", issuedOn: "16 May 2026", ministryId: "mohap", verificationCode: "FAHR-2026-MZ-3390" },
];

/** Items entities have escalated to the FAHR programme team. */
export const ESCALATIONS: Escalation[] = [
  { id: "es1", ministryId: "moe", subject: "Curriculum Feedback Synthesiser — data-sharing exception", kind: "Approval", raisedOn: "15 July 2026", raisedBy: "Ahmed Al Shamsi", status: "Open", detail: "Cross-emirate feedback records fall outside the entity's approved data scope. Federal sign-off requested.", submissionId: "s8" },
  { id: "es2", ministryId: "moccae", subject: "Token quota exceeded for Climate Policy cohort", kind: "Quota", raisedOn: "13 July 2026", raisedBy: "Shamma Al Hosani", status: "In progress", detail: "Consumption is at 105% of quota with six weeks of the cohort remaining." },
  { id: "es3", ministryId: "moi", subject: "Concierge escalation — learners unable to sign in with UAE PASS", kind: "Support", raisedOn: "11 July 2026", raisedBy: "Coaching Agent", status: "Open", detail: "Three learners report their UAE PASS sign-in returns them to the start page instead of their dashboard." },
];

/**
 * Federal AI guardrails shown on the governance screen. Toggling one is a
 * governance decision, so it belongs in the audit trail like any other.
 */
export const GOVERNANCE_POLICIES: GovernancePolicy[] = [
  { id: "humanInLoop", label: "Human-in-the-loop required for high-risk actions", description: "No high-risk AI output reaches a resident or a record without a named person approving it.", enabled: true, scope: "Federal", lastReviewed: "2 July 2026", owner: "FAHR Governance Office" },
  { id: "auditTrail", label: "Full immutable audit trail enabled", description: "Every agent action, decision and override is recorded and cannot be edited after the fact.", enabled: true, scope: "Federal", lastReviewed: "2 July 2026", owner: "FAHR Governance Office" },
  { id: "preventPII", label: "Block personal data from AI prompts", description: "Prompts are screened for personal data before they reach a model.", enabled: true, scope: "Federal", lastReviewed: "18 June 2026", owner: "FAHR Governance Office" },
  { id: "dataResidency", label: "Enforce UAE data residency for embeddings", description: "Knowledge sources and embeddings stay within approved UAE infrastructure.", enabled: true, scope: "Federal", lastReviewed: "18 June 2026", owner: "Ministry of Digital Economy and AI" },
  { id: "restrictPublicModels", label: "Restrict access to unapproved public models", description: "Only models on the federal approved list can be reached from the platform.", enabled: true, scope: "Federal", lastReviewed: "11 May 2026", owner: "FAHR Governance Office" },
  { id: "explainability", label: "Require an explainability trace for AI decisions", description: "Each AI-assisted decision carries the reasoning and sources behind it.", enabled: true, scope: "Entity", lastReviewed: "11 May 2026", owner: "Entity Admins" },
  { id: "pdplAlignment", label: "PDPL-aligned personal data handling", description: "Collection, processing and retention follow UAE Federal Decree-Law 45 of 2021, with a lawful basis recorded for every category of learner data.", enabled: true, scope: "Federal", lastReviewed: "2 July 2026", owner: "FAHR Governance Office" },
  { id: "sovereignHosting", label: "Sovereign model hosting", description: "Inference runs on UAE-sovereign infrastructure, with a defined path to LLMs on FAHR-owned GPUs.", enabled: true, scope: "Federal", lastReviewed: "18 June 2026", owner: "Ministry of Digital Economy and AI" },
  { id: "modelRegister", label: "Maintain the approved model register", description: "Every model reachable from the platform is named, versioned and re-approved each quarter.", enabled: true, scope: "Federal", lastReviewed: "11 May 2026", owner: "FAHR Governance Office" },
];

/** Accounts for the entity and federal user-administration screens. */
export const PLATFORM_USERS: PlatformUser[] = [
  { id: "u1", name: "Noura Al Kaabi", email: "noura.alkaabi@mohap.gov.ae", roleLabel: "Entity Admin", ministryId: "mohap", status: "Active", lastActive: "15 mins ago" },
  { id: "u2", name: "Mariam Al Zaabi", email: "mariam.alzaabi@mohap.gov.ae", roleLabel: "Department Manager", ministryId: "mohap", departmentId: "mohap-comms", status: "Active", lastActive: "20 mins ago" },
  { id: "u3", name: "Aisha Al Mansoori", email: "aisha.almansoori@mohap.gov.ae", roleLabel: "Federal Employee", ministryId: "mohap", departmentId: "mohap-comms", status: "Active", lastActive: "2 hours ago" },
  { id: "u4", name: "Ali Al Hammadi", email: "ali.alhammadi@mohap.gov.ae", roleLabel: "Department Manager", ministryId: "mohap", departmentId: "mohap-hospitals", status: "Active", lastActive: "Yesterday" },
  { id: "u5", name: "Hessa Al Nuaimi", email: "hessa.alnuaimi@mohap.gov.ae", roleLabel: "Federal Employee", ministryId: "mohap", departmentId: "mohap-hospitals", status: "Active", lastActive: "4 hours ago" },
  { id: "u6", name: "Yousef Al Ali", email: "yousef.alali@mohap.gov.ae", roleLabel: "Federal Employee", ministryId: "mohap", departmentId: "mohap-policy", status: "Active", lastActive: "6 days ago" },
  { id: "u7", name: "Mohammed Al Rayssi", email: "mohammed.alrayssi@mohap.gov.ae", roleLabel: "Content Author", ministryId: "mohap", departmentId: "mohap-comms", status: "Invited", lastActive: "—" },
  { id: "u8", name: "Ahmed Al Shamsi", email: "ahmed.alshamsi@moe.gov.ae", roleLabel: "Entity Admin", ministryId: "moe", status: "Active", lastActive: "1 hour ago" },
  { id: "u9", name: "Latifa Al Marzooqi", email: "latifa.almarzooqi@economy.gov.ae", roleLabel: "Entity Admin", ministryId: "econ", status: "Active", lastActive: "3 hours ago" },
  { id: "u10", name: "Hind Al Owais", email: "hind.alowais@fahr.gov.ae", roleLabel: "FAHR Programme Team", status: "Active", lastActive: "5 mins ago" },
  { id: "u11", name: "Sultan Al Rashdi", email: "sultan.alrashdi@fahr.gov.ae", roleLabel: "FAHR Governance Officer", status: "Active", lastActive: "45 mins ago" },
  { id: "u12", name: "Fahad Al Zeyoudi", email: "fahad.alzeyoudi@fahr.gov.ae", roleLabel: "Federal Leadership", status: "Active", lastActive: "Yesterday" },
];
